#!/usr/bin/env python3
"""Fixtures for check-delta.py.

Two layers. The parser cases feed Go source straight to `functions` and check
the names and ranges it finds. The decision cases build a throwaway git
repository with an old and a new tree, run the real enumeration over the real
diff, and check which names the body must carry. Most decision cases are
refusals, since a refusal is what the gate exists to produce and what an edit
can silently remove.

Run: python3 scripts/check-delta-selftest.py
"""

import importlib.util
import os
import pathlib
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True

HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("check_delta", HERE / "check-delta.py")
cd = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cd)

GO = '''package electrumx

import "errors"

// ErrX is a sentinel.
var ErrX = errors.New("x")

// commitRefresh merges a reply.
// Second doc line.
func (c *Client) commitRefresh(a int) error {
	if a < 0 {
		return ErrX
	}
	return nil
}

func plain() int { return 1 }

func stub()

// Host reports whether h is loopback.
func Host(h string) bool {
	return h == "localhost"
}

func (s *Set[K, V]) Len() int {
	return 0
}

func (Client) String() string {
	return "client"
}
'''


def parser_cases() -> list[str]:
    fs = cd.functions(GO, "electrumx")
    got = [(f.qualified, f.start, f.end) for f in fs]
    want = [
        ("Client.commitRefresh", 8, 15),   # doc comment included
        ("electrumx.plain", 17, 17),       # one-line body
        ("electrumx.stub", 19, 19),        # bodyless
        ("electrumx.Host", 21, 24),
        ("Set.Len", 26, 28),               # generic receiver
        ("Client.String", 30, 32),         # receiver without a name
    ]
    failures = []
    if got != want:
        failures.append(f"parser: got {got}, want {want}")
    if cd.functions("// Code generated by x. DO NOT EDIT.\npackage p\n\nfunc F() {\n}\n", "p"):
        failures.append("parser: a generated file must yield nothing")
    return failures


def run(cwd, *args):
    subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *args],
                   cwd=cwd, check=True, capture_output=True)


def repo(old: dict[str, str], new: dict[str, str]):
    """A repository whose `main` holds `old` and whose `work` holds `new`."""
    d = tempfile.TemporaryDirectory()
    run(d.name, "init", "-q", "-b", "main")
    for path, text in old.items():
        p = pathlib.Path(d.name, path); p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text)
    run(d.name, "add", "-A"); run(d.name, "commit", "-q", "-m", "old")
    run(d.name, "switch", "-q", "-c", "work")
    for path in set(old) - set(new):
        pathlib.Path(d.name, path).unlink()
    for path, text in new.items():
        p = pathlib.Path(d.name, path); p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text)
    run(d.name, "add", "-A"); run(d.name, "commit", "-q", "-m", "new", "--allow-empty")
    return d


OLD = {"x/a.go": '''package x

// A does a.
func A() int {
	return 1
}

// B does b.
func B() int {
	return 2
}

func (t *T) C() int {
	return 3
}

func (u *U) C() int {
	return 4
}

func Gone() {
}
''', "x/a_test.go": "package x\n\nfunc TestA() {\n}\n"}

NEW = {"x/a.go": '''package x

// A does a, differently.
func A() int {
	return 1
}

// B does b.
func B() int {
	return 2
}

func (t *T) C() int {
	return 30
}

func (u *U) C() int {
	return 4
}

func Added() int {
	return 5
}
''', "x/a_test.go": "package x\n\nfunc TestA() {\n\tA()\n}\n", "y/b.go": "package y\n\nfunc New() int {\n\treturn 1\n}\n"}

# Only a deletion inside a body: the new side shows nothing at those lines.
DELETE_ONLY_NEW = {"x/a.go": OLD["x/a.go"].replace("\treturn 3\n", "")}

CASES = [
    # (name, old tree, new tree, body, names the body is missing)
    ("doc comment, body and addition are enumerated; a test file and a removed function are not",
     OLD, NEW, "", ["A", "T.C", "Added", "New"]),
    ("every name present passes", OLD, NEW,
     "`A` and `T.C` and `Added` and `y.New` are named.", []),
    ("a bare name for a shared method name is not enough", OLD, NEW,
     "A, C, Added, New.", ["T.C"]),
    ("a longer identifier does not stand for the name", OLD, NEW,
     "Added, T.C, New, and Analyse.", ["A"]),
    ("a change made only by deleting lines counts", OLD, DELETE_ONLY_NEW, "", ["T.C"]),
    ("no change to non-test Go needs nothing", OLD, {**OLD, "x/a_test.go": "package x\n"}, "", []),
]


def decision_cases() -> list[str]:
    failures = []
    for name, old, new, body, want_missing in CASES:
        with repo(old, new) as d:
            cwd = os.getcwd()
            os.chdir(d)
            try:
                problems, _total = cd.check_names("main", "work", body)
            finally:
                os.chdir(cwd)
        got_missing = [ln.split()[0] for ln in problems[2:]]
        ok = got_missing == want_missing
        print(f"{'OK  ' if ok else 'FAIL'}  {name}")
        if not ok:
            failures.append(f"{name}: missing {got_missing}, want {want_missing}")
    return failures


def main() -> int:
    failures = parser_cases()
    print(f"{'FAIL' if failures else 'OK  '}  parser: six declaration shapes and a generated file")
    failures += decision_cases()
    if failures:
        print("\ncheck-delta-selftest: " + "\n".join(failures), file=sys.stderr)
        return 1
    print(f"\ncheck-delta-selftest: {len(CASES) + 1} cases OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
