#!/usr/bin/env python3
"""Fixtures for check-delta.py.

Two layers. The parser cases feed Go source straight to `functions` and check
the names and ranges it finds, with the shapes gofmt emits and the shapes that
would fool a line-based reading: a signature spanning lines, a raw string with
a brace in column 0 and a `++` line, a brace inside a comment, a rune and a
string, a struct literal as a result type, a brace inside a type parameter's
constraint. The decision cases build a throwaway git repository with an old
and a new tree, run the real enumeration over the real diff, and check which
names the body must carry. Most decision cases are refusals, since a refusal
is what the gate exists to produce and what an edit can silently remove.

The repositories are built and read under an empty global git configuration,
so a reader's `commit.gpgsign` or hooks path cannot change a case; the settings
that could change the diff's text or its hunks, the prefixes and the
algorithm, are set locally in their own cases to show the reader is not
affected by them.

Run: python3 scripts/check-delta-selftest.py
"""

import importlib.util
import os
import pathlib
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
os.environ["GIT_CONFIG_GLOBAL"] = os.devnull
os.environ["GIT_CONFIG_NOSYSTEM"] = "1"

HERE = pathlib.Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("check_delta", HERE / "check-delta.py")
cd = importlib.util.module_from_spec(spec)
spec.loader.exec_module(cd)

GO = '''package electrumx

import "errors"

// ErrX is a sentinel.
var ErrX = errors.New("x")

// commitRefresh merges a reply.
// Second doc line.
func (c *Client) commitRefresh(a int) error {
	if a < 0 {
		return ErrX
	}
	return nil
}

func plain() int { return 1 }

func stub()

// Host reports whether h is loopback.
func Host(h string) bool {
	return h == "localhost"
}

func (s *Set[K, V]) Len() int {
	return 0
}

func (Client) String() string {
	return "client"
}

func Build(
	a int,
	b int,
) int {
	return a + b
}

func Raw() string {
	return `
}
++ marker
func notADeclaration() {
`
}

func One() { // }
	return
}

func Rune() byte { return '{' }

func Quoted() string { return "}" }

func Shape() struct{ n int } {
	return struct{ n int }{1}
}

func Constrained[T interface{ ~int }](x T) T {
	return x
}

func Escaped() string { return "q\\"}" }
'''


def parser_cases() -> list[str]:
    fs = cd.functions(GO, "electrumx")
    got = [(f.qualified, f.start, f.end) for f in fs]
    want = [
        ("Client.commitRefresh", 8, 15),   # doc comment included
        ("electrumx.plain", 17, 17),       # one-line body
        ("electrumx.stub", 19, 19),        # bodyless
        ("electrumx.Host", 21, 24),
        ("Set.Len", 26, 28),               # generic receiver
        ("Client.String", 30, 32),         # receiver without a name
        ("electrumx.Build", 34, 39),       # signature over several lines
        ("electrumx.Raw", 41, 47),         # raw string holding `}` and `func` in column 0
        ("electrumx.One", 49, 51),         # `}` inside a comment
        ("electrumx.Rune", 53, 53),        # `{` as a rune literal
        ("electrumx.Quoted", 55, 55),      # `}` inside a string
        ("electrumx.Shape", 57, 59),       # struct literal as the result type
        ("electrumx.Constrained", 61, 63), # brace inside a type parameter's constraint
        ("electrumx.Escaped", 65, 65),     # escaped quote before a `}` in a string
    ]
    failures = []
    if got != want:
        for g, w in zip(got, want):
            if g != w:
                failures.append(f"parser: got {g}, want {w}")
        if len(got) != len(want):
            failures.append(f"parser: {len(got)} functions, want {len(want)}: {got}")
    if cd.functions("// Code generated by x. DO NOT EDIT.\npackage p\n\nfunc F() {\n}\n", "p"):
        failures.append("parser: a generated file must yield nothing")
    # An unterminated string is not Go, but it must not shift the line count of
    # what follows it.
    fs = cd.functions('package p\n\nvar s = "unterminated\n\nfunc F() {\n}\n', "p")
    if [(f.qualified, f.start, f.end) for f in fs] != [("p.F", 5, 6)]:
        failures.append(f"parser: an unterminated string shifted the lines: {[(f.qualified, f.start, f.end) for f in fs]}")
    return failures


def run(cwd, *args):
    subprocess.run(["git", "-c", "user.name=t", "-c", "user.email=t@t", *args],
                   cwd=cwd, check=True, capture_output=True)


def repo(old: dict[str, str], new: dict[str, str], config=()):
    """A repository whose `main` holds `old` and whose `work` holds `new`."""
    d = tempfile.TemporaryDirectory()
    run(d.name, "init", "-q", "-b", "main")
    for key, value in config:
        run(d.name, "config", key, value)
    for path, text in old.items():
        p = pathlib.Path(d.name, path); p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text)
    run(d.name, "add", "-A"); run(d.name, "commit", "-q", "-m", "old")
    run(d.name, "switch", "-q", "-c", "work")
    for path in set(old) - set(new):
        pathlib.Path(d.name, path).unlink()
    for path, text in new.items():
        p = pathlib.Path(d.name, path); p.parent.mkdir(parents=True, exist_ok=True); p.write_text(text)
    run(d.name, "add", "-A"); run(d.name, "commit", "-q", "-m", "new", "--allow-empty")
    return d


A_GO = '''package x

// A does a.
func A() int {
	return 1
}

// B does b.
func B() int {
	return 2
}

func (t *T) C() int {
	return 3
}

func (u *U) C() int {
	return 4
}

func Gone() {
}

func Build(
	a int,
	b int,
) int {
	return a + b
}
'''

OLD = {"x/a.go": A_GO, "x/a_test.go": "package x\n\nfunc TestA() {\n}\n",
       "y/b.go": "package y\n\nfunc Old() int {\n\treturn 1\n}\n"}

NEW = {"x/a.go": A_GO.replace("// A does a.", "// A does a, differently.")
                     .replace("\treturn 3\n", "\treturn 30\n")
                     .replace("func Gone() {\n}\n", "func Added() int {\n\treturn 5\n}\n"),
       "x/a_test.go": "package x\n\nfunc TestA() {\n\tA()\n}\n",
       "y/b.go": "package y\n\nfunc Old() int {\n\treturn 1\n}\n\nfunc New() int {\n\treturn 1\n}\n"}

# Only a deletion inside a body: the new side shows nothing at those lines.
DELETE_ONLY_NEW = {**OLD, "x/a.go": A_GO.replace("\treturn 3\n", "")}

# The multi-line signature's body edited and nothing else.
BUILD_NEW = {**OLD, "x/a.go": A_GO.replace("\treturn a + b\n", "\treturn a - b\n")}

# One file gone, everything else the same.
DELETED_FILE_NEW = {k: v for k, v in OLD.items() if k != "y/b.go"}

# A new file with one function.
ADDED_FILE_NEW = {**OLD, "z/c.go": "package z\n\nfunc G() int {\n\treturn 1\n}\n"}

# The file moved within its directory, one method edited inside it.
RENAMED_NEW = {"x/renamed.go": A_GO.replace("\treturn 3\n", "\treturn 30\n"),
               "x/a_test.go": OLD["x/a_test.go"], "y/b.go": OLD["y/b.go"]}

# The file moved to another directory, one method edited only by deletion.
MOVED_NEW = {"w/a.go": A_GO.replace("package x", "package w").replace("\treturn 3\n", ""),
             "x/a_test.go": OLD["x/a_test.go"], "y/b.go": OLD["y/b.go"]}

SPACE_OLD = {"x/my file.go": "package x\n\nfunc F() int {\n\treturn 1\n}\n"}
SPACE_NEW = {"x/my file.go": "package x\n\nfunc F() int {\n\treturn 2\n}\n"}

CALL = "package %s\n\ntype Client struct{}\n\nfunc (c *Client) Call() int {\n\treturn %d\n}\n"
COLLIDE_OLD = {"p/c.go": CALL % ("p", 1), "q/c.go": CALL % ("q", 1)}
COLLIDE_NEW = {"p/c.go": CALL % ("p", 2), "q/c.go": CALL % ("q", 1)}

# Four functions with identical bodies, reordered: which of them a diff calls
# changed depends on the algorithm, so the algorithm is named and the answer
# is the same whatever the reader's configuration says.
def same_bodies(order):
    return "package r\n\n" + "".join(f"func {n}() int {{\n\treturn 1\n}}\n\n" for n in order)


REORDER_OLD = {"r/f.go": same_bodies("ABCD")}
REORDER_NEW = {"r/f.go": same_bodies("CADB")}

CASES = [
    # (name, old tree, new tree, body, names the body is missing, local git config)
    ("doc comment, body and addition are enumerated; a test file and a removed function are not",
     OLD, NEW, "", ["A", "T.C", "Added", "New"], ()),
    ("every name present passes", OLD, NEW,
     "`A` and `T.C` and `Added` and `y.New` are named.", [], ()),
    ("a bare name for a shared method name is not enough", OLD, NEW,
     "A, C, Added, New.", ["T.C"], ()),
    ("a longer identifier does not stand for the name, on either side", OLD, NEW,
     "Added, T.C, New, Analyse and xA.", ["A"], ()),
    ("a change made only by deleting lines counts", OLD, DELETE_ONLY_NEW, "", ["T.C"], ()),
    ("a body change under a signature spanning lines is attributed", OLD, BUILD_NEW, "", ["Build"], ()),
    ("a deleted file's functions are reported, not required", OLD, DELETED_FILE_NEW, "", [], ()),
    ("an added file's functions are required", OLD, ADDED_FILE_NEW, "", ["G"], ()),
    ("a renamed file requires only the function edited in it", OLD, RENAMED_NEW, "", ["T.C"], ()),
    ("a file moved to another directory pairs each function with itself", OLD, MOVED_NEW, "", ["T.C"], ()),
    ("a path with a space is read", SPACE_OLD, SPACE_NEW, "", ["F"], ()),
    ("a method whose type and name recur in another directory needs the directory",
     COLLIDE_OLD, COLLIDE_NEW, "Client.Call is changed.", ["p.Client.Call"], ()),
    ("diff.noprefix in the reader's configuration changes nothing",
     OLD, NEW, "", ["A", "T.C", "Added", "New"], (("diff.noprefix", "true"), ("diff.mnemonicPrefix", "true"))),
    ("reordered identical bodies: the answer under the named algorithm",
     REORDER_OLD, REORDER_NEW, "", ["C", "A", "D", "B"], ()),
    ("reordered identical bodies: diff.algorithm in the reader's configuration changes nothing",
     REORDER_OLD, REORDER_NEW, "", ["C", "A", "D", "B"], (("diff.algorithm", "patience"), ("diff.indentHeuristic", "false"))),
    ("no change to non-test Go needs nothing", OLD, {**OLD, "x/a_test.go": "package x\n"}, "", [], ()),
]


def decision_cases() -> list[str]:
    failures = []
    for name, old, new, body, want_missing, config in CASES:
        with repo(old, new, config) as d:
            cwd = os.getcwd()
            os.chdir(d)
            try:
                problems, _total = cd.check_names("main", "work", body)
                text = cd.listing("main", "work")
            finally:
                os.chdir(cwd)
        got_missing = [ln.split()[0] for ln in problems[2:]]
        ok = got_missing == want_missing
        if name.startswith("doc comment"):
            # The listing labels each function; the labels are what a reader acts on.
            for want in ("added    Added", "added    New", "changed  A ", "changed  T.C", "removed  x.Gone"):
                if want not in text:
                    ok = False
                    failures.append(f"{name}: listing lacks {want!r}:\n{text}")
        if name.startswith("a deleted file") and "removed  y.Old" not in text:
            ok = False
            failures.append(f"{name}: listing does not report the removed function:\n{text}")
        if name.startswith("a file moved") and "removed" in text:
            ok = False
            failures.append(f"{name}: a moved function was reported as removed:\n{text}")
        print(f"{'OK  ' if ok else 'FAIL'}  {name}")
        if got_missing != want_missing:
            failures.append(f"{name}: missing {got_missing}, want {want_missing}")
    return failures


def main() -> int:
    failures = parser_cases()
    print(f"{'FAIL' if failures else 'OK  '}  parser: fourteen declaration shapes, a generated file, an unterminated string")
    failures += decision_cases()
    if failures:
        print("\ncheck-delta-selftest: " + "\n".join(failures), file=sys.stderr)
        return 1
    print(f"\ncheck-delta-selftest: {len(CASES) + 1} cases OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
